@startuml example-erm-diagram
' diagram direction
left to right direction
' hide the (E) in the entity name
hide circle
' avoid problems with angled crows feet
skinparam linetype ortho
' Remove shadows
skinparam shadowing false

entity Address {
  * <&key> **id** : char(5)
  --
  * street : varchar(255)
  * zipCode : char(5)
  * city : varchar(255)
  * country : varchar(255)
  ...
}

entity Student {
  * <&key> **id** : char(5)
  --
  * firstName : varchar(255)
  * lastName : varchar(255)
  * addressID : char(5) <<FK>>
  ...
}

entity Subject {
  * <&key> **id** : char(2)
  --
  * name : varchar(255)
  ...
}

entity Mark {
  * <&key> **studentId** : char(5) <<FK>>
  * <&key> **subjectId** : char(2) <<FK>>
  --
  mark : float
  ...
}

Address ||--|{ Student
Student ||--o{ Mark
Mark }o--|| Subject

@enduml