@startuml
left to right direction
skinparam shadowing false


' different paths in plantUML preview, VS Code preview and build script
!$file = "source/hello_world.svg"
!$file_vscode = "{plantumlsdir}/" + $file
!$file_build_script = "{docdir}/{plantumlsdir}/" + $file
!if (%file_exists($file))
!elseif (%file_exists($file_vscode))
  !$file = $file_vscode
!elseif (%file_exists($file_build_script))
  !$file = $file_build_script
!else
  ' disabled, the first `%file_exists($file)` doesnt work in VSCode
  '!$file = ""
!endif
!assert $file != "" : "File not found!"

sprite foo1 $file
rectangle diagram #fff [
  <$foo1>
  '<img:"$file">
]

note as code #fff
  ""<color:lightgrey>01</color> actor Human""
  ""<color:lightgrey>02</color> usecase World #dff""
  ""<color:lightgrey>03</color>""
  ""<color:lightgrey>04</color> note right of Human: Hello""
end note

code ..> diagram: Asciidoctor

note top of code: textliche Beschreibung\nin PlantUML-Notation
note bottom of diagram: generiertes Diagramm
@enduml
