include::header.inc.adoc[]

Ziel: Organisation von Aufgaben im Team mit Hilfe von *GitHub Issues* an einem gemeinsamen Repository auf *GitHub*

include::hinweise-windows-labor.inc.adoc[]

== Praktikumsaufgaben Teil 4 - Teamarbeit: Issues

////
- *GitHub*: _Collaborators_, _Issues_, _Pull request_, _Projects_
- *Git*: _pull_, _branches_, _merges_, _conflicts_, _tags_
- *AsciiDoc*: _includes_, _callouts_, _Q&A (Glossar)_, ...
////

Die Bearbeitung der Aufgabe 1 und zum Teil in Aufgabe 2 erfolgt in Ihrem Team-Repository *htwd-se-example-teamproject* aus dem letzten Praktikum. In Aufgabe 3 nehmen Sie Ihr Repository *htwd-se-example-project*.

{section-separator}


=== 1. GitHub: Issues

NOTE: Issues are a great way to keep track of tasks, enhancements, and bugs for your projects. They’re kind of like email—except they can be shared and discussed with the rest of your team. Most software projects have a bug tracker of some kind. GitHub’s tracker is called Issues, and has its own section in every repository. - https://guides.github.com/features/issues/[GitHub]

GitHub bietet mit dem Bereich *Issues* eine Möglichkeit anstehende Aufgaben, aufgetretene Probleme und mögliche Verbesserungen zentral in Ihrem Projekt innerhalb Ihres Repository zu verwalten und zu diskutieren.

:imageTitle: Screenshot: Bereich Issues auf GitHub
:imageFile: screenshot_github_issues.png
.{imageTitle}
image::{imageFile}["{imageTitle}", width=800, link="{imagesdir}/{imageFile}"]

Jeder Issue (Aufgabe, Ticket, ...) besteht aus einem *Titel* und der *Beschreibung* des Sachverhaltes. Zusätzlich können zur besserer Verwaltung noch *Assignees* (Beauftrage), *Labels* und weitere Kriterien hinzugefügt werden. Ebenfalls kann über *Kommentar* der Issue diskutiert und mit Anmerkungen versehen werden. Eine detailierte Beschreibung finden Sie in dem Guide: https://guides.github.com/features/issues/[Mastering Issues]

Bei Verwendung bestimmter *Keywords* (https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords[Closing issues using keywords]) in den Commit Messages können *referenzierte Issues* automatisch geschlossen werden.

.Hinweise: Verwenden von Referenzen in Issue-Kommentaren und Commits
[%collapsible]
====
=====
In den Issues und Commits können in den Kommentaren/Mitteilungen Verweise auf andere Elemente verwendet werden. Diese werden von GitHub automatisch verlinkt.

[#table_verweise]
.Ausgewählte Verweise
[cols="1,1,3"]
|===
| *Issue*  | Nummer      | `#2`
| *Commit* | SHA hash    | `5000fb638483c95d5f0346181af32096db2d23ff`
| *User*   | Accountname | `@account`
|===

Siehe auch: https://help.github.com/en/articles/autolinked-references-and-urls[Autolinked references and URLs]

Beispiele:

* Commit Message:
** `Setze Erweiterung aus Issue #2 um`
** `Setze Erweiterung um (#2)`
* Commit Message mit automatischem Schließen der zugehörigen Issue:
** `Korrigiere Fehler (close #2)`
* Issue Kommentar:
** `... siehe Commit 479bcfca71f10423c0f1181853017b83af062c46`
=====
====

==== Aufgabe 1.1 - Issues anlegen, kommentieren

Jeder im Team des Teamprojektes *htwd-se-example-teamproject* denkt sich eine kleine machbare Änderung oder Erweiterung für die Dokumentation in AsciiDoc aus.

.Aufgabe - icon:users[] Person A, B, C
1. Legen Sie jeweils zwei neue *Issue* in Ihrem Teamprojekt an. Denken Sie sich hierfür eine kleine, sinnvolle und umsetzbare Erweiterung für Ihre Dokumentation (AsciiDoc) im Projekt aus. Vergeben Sie einen Titel, eine Beschreibung und ein Label `asciidoc`.
2. Schauen Sie sich die Issues Ihrer Teammitglieder an und diskutieren (kommentieren) Sie sie.
3. Weißen Sie sich gegenseitig über Assignees je zwei Issue zu und ergänzen Sie ein Label `documentation`.

==== Aufgabe 1.2 - Issues bearbeiten, referenzieren

.Aufgabe - icon:users[] Person A, B, C
. Setzen Sie Ihre *erste* zugewiesene Issue um und nehmen Sie in der Commit Message eine *Referenz* der zugehörigen Issue auf.
+
.Bspw. Commit Message mit Referenz zur Issue:
----
Korrigiere falschen Teamnamen (Issue #6)
----
. Nehmen Sie in der Issue eine Referenz zu Ihrem Commit als Kommentar auf und schließen Sie die fertig bearbeitete Issue am Ende über GitHub.
+
.Bspw. Issue Kommentar auf GitHub mit Referenz zum Commit:
----
Änderung der Teamnamen in Commit 5000fb638483c95d5f0346181af32096db2d23ff erfolgt.
----
. Setzen Sie Ihre *zweite* zugewiesene Issue um und nehmen Sie in der Commit Message eine *Referenz mit Schlüsselwort zur automatischen Schließung* der zugehörigen Issue auf.
+
.Bspw. Commit Message mit Referenz zur Issue und automatischer Schließung:
----
Ändere Inhalt (close #6)
----
. Schauen Sie sich die Issues (Open & Closed) und die dazu entstandenen Kommentare und Verweise durch die Referenzen an.

==== Aufgabe 1.3 - Aufgabenlisten in Issues

In den Issue-Beschreibungen können auch Aufgabenlisten angelegt werden. Dies können Teilschritte einer Issue sein oder eine Art Check-Liste, ob bspw. alle genannten Teammitglieder diese erfüllt haben. Bei Bedarf können Teilaufgaben auch in neue Issues umgewandelt werden.

Siehe auch: https://docs.github.com/de/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists[Informationen zu Aufgabenlisten]

.Hinweise: Beispiele für Aufgabenlisten in Issues
[%collapsible]
====
=====
.Beispiel für Teilaufgaben:
[code, markdown]
----
Use-Case UC01 bearbeiten

- [ ] Kurzbeschreibung, Akteure und Vorbedingung erfassen
- [ ] Standardablauf ausarbeiten
- [ ] Szenario mit konkreten Daten zum Standardablauf ausarbeiten
- [ ] ...
----

.Beispiel für eine Check-Liste:
[code, markdown]
----
Macht euch mit Aufgabenlisten vertraut.

- [ ] Person A
- [ ] Person B
- [ ] Person C
----
=====
====

.Aufgabe - icon:users[] Person A, B, C
. Erstellen Sie jeweils eine neue *Issue* und verwenden Sie in der Beschreibung eine *Aufgabenliste*.
. Wandeln Sie eine der *Teilaufgaben* in der Aufgabenliste in eine neue *Issue* um.
. Schauen Sie sich die eben erstellten Issues an.


{section-separator}

=== 2. Issues mit Filtern im Überblick behalten

In der *Issues* Anzeige von GitHub werden alle vorhandenen *Issues* und
*Pull Requests* aufgelistet. Standardmäßig ist die Sicht mit `is:issue is:open` auf offene Issues gefiltert.

:imageTitle: Issue-Ansicht in GitHub
:imageFile: screenshot_github_issues_filter.jpg
.{imageTitle}
image::{imageFile}["{imageTitle}", width=800, link="{imagesdir}/{imageFile}"]

.Hinweise zu den Filtermöglichkeiten
[%collapsible]
====
=====
Für eine gezielte Sicht auf bestimmt Einträge, gibt es ein Vielzahl an Filtermöglichkeiten und deren Kombination. Ausgewählte finden Sie in der <<table_filterkritterien>> und eine komplette Liste und weitere Informationen unter folgenden Links:

- https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests[GitHub - Searching issues and pull requests]
- https://help.github.com/en/github/searching-for-information-on-github/understanding-the-search-syntax[GitHub - Understanding the search syntax]
- https://help.github.com/en/github/searching-for-information-on-github/sorting-search-results[GitHub - Sorting search results].

.Ausgewählte Filterkritterien
[#table_filterkritterien]
[cols="1,3"]
|===
| Filter      | Beschreibung

| `is:pr`     | Pull-Requests
| `is:issue`  | Issues
| `is:open`   | offen
| `is:closed` | geschlossen
| `author:USERNAME` | von einem Nutzer erstellt
| `assignee:USERNAME` | einem Nutzer zugewiesen
| `label:LABEL` | einem Label zugeordnet
| `milestone:MILESTONE` | einem Meilenstein zugeordnet
| `project:PROJECT` | einem Projekt zugeordnet
|===

.Filterkritterien für fehlende Angaben
[cols="1,3"]
|===
| Filter         | Beschreibung

| `no:label`     | keinem Label zugeordnet
| `no:milestone` | keinem Meilenstein zugeordnet
| `no:project`   | keinem Projekt zugeordnet
| `no:assignee`  | keinem Nutzer zugeordnet
|===

Ein Filter mit `is:issue is:open no:assignee` ist sehr hilfreich, um offenen *Issues*, welchen keine Nutzer zur Bearbeitung zugeordnet sind, im Blick zu haben. Über ein `sort:created-asc` lässt sich die Ausgabe zeitlich sortieren.

NOTE: Filter lassen sich aktuell nicht direkt in GitHub speichern, aber die Seiten-URL enthält nach einer Suche den Filter und lässt sich so als Bookmark speichern. Für das obere Beispiel würde die URL am Ende wie folgt aussehen: +
`/issues?q=is:open+is:issue+no:assignee+sort:created-asc`
=====
====

==== Aufgabe 2.1 - Issues filtern

Listen Sie in Ihrem Team-/Projekt-Repository oder einem anderen Repository (bspw. https://github.com/neovim/neovim/issues[neovim Issues]) Issues nach folgenden Filtern auf:

- Alle geschlossenen Issues und Pull-Requests seit Semesterbeginn
- Alle Issues die keinem Nutzer (Assignee) zugeordnet sind
- Alle offenen Issues die keinem Projekt oder Meilenstein zugeordnet sind
- Alle Issues die Sie erstellt haben und einem bestimmten Label
- Alle offenen Issues denen Sie zugeordnet sind
- Alle Issues in denen ein bestimmtes Wort (bspw. "Meeting") vorkommt
- Alle Issues und Pull-Requests mit mehr als 2 Kommentaren

Schauen Sie sich weiteren Filtermöglichkeiten über den Button kbd:[Filters ▼] oder Schnellfilter im Listenkopf (Author, Label, Projects, Milestines, Asignees, Sort) an und denken Sie sich ein paar weitere nützliche Filtermöglichkeiten für Ihr Projekt aus.

////
comments:>=2
////

include::sitemap.inc.adoc[]
